defaults:
  - visualization: eval

num_workers: 0
batch_size: 1
cuda: 0
weight_name: latest
checkpoint_dir: /dpb/models
model_name: PointGroup-PAPER_latest

enable_cudnn: true
enable_dropout: false
voting_runs: 1
precompute_multi_scale: true

data:
  task: custom
  class: ufg_inference.PLYInferenceDataset
  dataroot: /dpb/data
  fold: []

tracker_options:
  full_res: true
  make_submission: true
  ply_output: eval_output.ply

hydra:
  run:
    dir: /dpb/output/eval/${now:%Y-%m-%d_%H-%M-%S}

