defaults: 
  - visualization: eval

num_workers: 0
batch_size: 1
cuda: 0
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/dpb/models"
model_name: "PointGroup-PAPER_latest"
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1
data: 
  fold: []

hydra:
  run:
    dir: /dpb/output/eval/${now:%Y-%m-%d_%H-%M-%S}
